# Generated by Django 4.2.1 on 2023-05-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_month_name_alter_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='need', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('need', 'Need'), ('want', 'Want'), ('saving', 'Saving')], default='need', max_length=6, unique=True),
        ),
    ]
