# Generated by Django 4.2.1 on 2023-05-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_month_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.ForeignKey(default='may', on_delete=django.db.models.deletion.CASCADE, to='app.month'),
        ),
    ]
