# Generated by Django 4.2.1 on 2023-05-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_expense_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.ForeignKey(default='May', on_delete=django.db.models.deletion.CASCADE, to='app.month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='need', max_length=9, unique=True),
        ),
    ]
